name: Fetch FRED Data

on:
  workflow_dispatch:
    inputs:
      series_ids:
        description: 'Comma-separated list of series to fetch (e.g., UMCSENT,GDPC1,CPIAUCSL)'
        required: true
        default: 'UMCSENT'

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run selected series
        env:
          SERIES_IDS: ${{ github.event.inputs.series_ids }}
          FRED_API_KEY: a6bd75c0ecd1b95bfdc5c3b9f5a97f6e
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python scripts/run_selected_series.py <<< "${{ github.event.inputs.series_ids }}"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: fred-data
          path: outputs/*
